version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Cake.Core
    versions:
    - "> 1.0.0, < 2"
  - dependency-name: Cake.Common
    versions:
    - "> 1.0.0, < 2"
  - dependency-name: Cake.Testing
    versions:
    - "> 1.0.0, < 2"